### ISSUE TITLE
aws_autoscaling_group that is using tags can't work with terratag

### ISSUE THREAD

**Issue by ezraroi** [env0/terratag#101]
Looks like you count on the fact that only the `tag` way to add tags to `autoscaling_group`. We use some modules that defines the `autoscaling_group` for us such as `consul_cluster` for example and we do not control if they use `tags` or `tag`.

For this we need to custom method that tags `autoscaling_group` to use tags or tag based on the existing code.

Error example:
```
╷
│ Error: Conflicting configuration arguments
│
│   with module.consul_cluster.module.consul_cluster.aws_autoscaling_group.autoscaling_group,
│   on .terraform/modules/consul_cluster.consul_cluster/modules/consul-cluster/main.terratag.tf line 39, in resource "aws_autoscaling_group" "autoscaling_group":
│   39:   tags = flatten(
│   40:     [
│   41:       {
│   42:         key                 = "Name"
│   43:         value               = var.cluster_name
│   44:         propagate_at_launch = true
│   45:       },
│   46:       {
│   47:         key                 = var.cluster_tag_key
│   48:         value               = var.cluster_tag_value
│   49:         propagate_at_launch = true
│   50:       },
│   51:       var.tags,
│   52:     ]
│   53:   )
│
│ "tags": conflicts with tag
```

**Comment by yaronya** [comment]
@ezraroi can you please attach some TF code example that generates this error? 🙏

**Comment by ezraroi** [comment]
```
module "consul_cluster" {
  source  = "hashicorp/consul/aws//modules/consul-cluster"
  version = "0.11.0"

  ami_id = var.ami_id == null ? data.aws_ami.consul.image_id : var.ami_id
  cluster_name = substr(local.cluster_name, 0, 32)
  instance_type = var.instance_type
  vpc_id = data.aws_vpc.this.id
  subnet_ids = data.aws_subnet_ids.this.ids
  associate_public_ip_address = false
  cluster_size = var.num_servers
  cluster_tag_key = var.consul_cluster_tag_key
  cluster_tag_value = local.cluster_name
  enable_https_port = false
  enable_iam_setup = true
  enabled_metrics = ["GroupDesiredCapacity", "GroupInServiceInstances"]
  ssh_key_name    = var.ssh_key_name
  root_volume_size = var.root_volume_size
  root_volume_type = var.root_volume_type
  http_api_port = var.http_api_port
  serf_lan_port = var.serf_lan_port

  allowed_inbound_cidr_blocks = ["10.0.0.0/8", "172.29.0.0/16"]
  allowed_ssh_cidr_blocks     = ["10.0.0.0/8", "172.29.0.0/16"]

  tags = flatten(
  [
    local.module_default_tags,
    var.tags,
  ]
  )

  user_data = var.user_data == null ? data.template_file.user_data_server.rendered : var.user_data
}
```

**Comment by ezraroi** [comment]
In high level, as `aws_autoscaling_group` supports both `tag` and `tags` what will happen Not my code is creating the `aws_autoscaling_group` directly and the 3th party module defines it for me and decided to use the `tags` way and not `tag`

**Comment by jeffliu527** [comment]
met with the same issue while creating a aws bastion server using: https://github.com/Guimove/terraform-aws-bastion , if @ezraroj 's solution cant be accepted, pls advise how to fix this issue.

Error message:

│ Error: Conflicting configuration arguments
│ 
│   with module.bastion.module.bastion.aws_autoscaling_group.bastion_auto_scaling_group,
│   on .terraform/modules/bastion.bastion/main.terratag.tf line 330, in resource "aws_autoscaling_group" "bastion_auto_scaling_group":
│  330:   tags = concat(
│  331:     tolist([tomap({
│  332:       "key"                 = "Name"
│  333:       "value"               = "ASG-${local.name_prefix}"
│  334:       "propagate_at_launch" = true
│  335:     })]),
│  336:     local.tags_asg_format
│  337:   )
│ 
│ "tags": conflicts with tag

**Comment by TomerHeber** [comment]
@yaronya - I see there is code that handles both tags and tag. Could we find some time to discuss the issue? I'm not 100% sure I understand the full picture. Thanks!

**Comment by yaronya** [comment]
@TomerHeber sure, feel free to ping me or any other team member via our Slack channel and ask.
