### ISSUE TITLE
Tests hang on `terraform validate` failures

### ISSUE THREAD

**Issue by yaronya** [env0/terratag#106]
We had a `terraform validate` commands that failed on the `google_map_labels` fixture.

Expected behavior: thrown error from `terraform validate` should be included in test matrix results.
Actual behavior: `terraform validate` command hangs. See [example](https://github.com/env0/terratag/runs/4277428258?check_suite_focus=true).

**Comment by TomerHeber** [comment]
@yaronya - I'm unclear why would `terraform validate` hang? The example link is no longer valid. Is there more information you can share?

**Comment by yaronya** [comment]
> @yaronya - I'm unclear why would `terraform validate` hang? The example link is no longer valid. Is there more information you can share?

Yeah, GH only persist those for some limited amount of time 😞 
I think the issue was that when one TF file is malformed and fails on `terraform validate` - then the GH action simply hangs and times out instead of failing fast.

You can try to reproduce it easily by modifying one of the TF files to be malformed that it would fail on `terraform validate` and see what happens.
If that doesn't happen anymore - then let's close this issue

**Comment by TomerHeber** [comment]
Unable to reproduce.
In all cases `terraform validate` had returned an error and did not hangup.
