### ISSUE TITLE
Terraform 1.1.0 Support

### ISSUE THREAD

**Issue by WillGodsall** [env0/terratag#107]
Running terratag on the newly released terraform 1.1.0 results in the following error message

> 2021/12/09 11:13:49 Terratag only supports Terraform from version 0.11.x and up to 1.0.x - your version says  Terraform v1.1.0
on windows_amd64

Cheers!

**Comment by yaronya** [comment]
Hi @WillGodsall!
Thanks for pointing that out as this is a brand new release from hashicorp 👍 
We're planning on supporting it soon but we're also accepting pull requests so feel free to suggest one 😉

**Comment by WillGodsall** [comment]
Hi @yaronya 
I've given it a go! 😅
#108
