### ISSUE TITLE
How to handle multiple TF workspaces? 

### ISSUE THREAD

**Issue by dsfrederic** [env0/terratag#112]
I've got a workspace for each env. 

Is there a way to include tags based on the current terraform workspace?

**Comment by RLRabinowitz** [comment]
Hey @dsfrederic , how about using `terraform workspace show` command to decide the tag?

Something along the lines of:
```
my_workspace=$(terraform workspace show)
terratag -dir=foo/bar -tags={\"environment_id\": \"$my_workspace\"}
```

**Comment by yaronya** [comment]
Closing as answer seems like a reasonable solution to the use case
