### ISSUE TITLE
Support go module import

### ISSUE THREAD

**Issue by luckoseabraham** [env0/terratag#117]
I would like to use terratag as a golang module instead of binary due to lack of control of the runtime where the executions are done. Our runtime package involves more than terratag. So it makes sense to just import this as a module and run it.

But the initialization seems to be done in the main package and needs to be duplicated. https://github.com/env0/terratag/blob/master/main.go#L51-L154 

It would be great if we can move the above mentioned lines to another package so its easier to import into other go apps.

Would you be open for a pull request ?

**Comment by yaronya** [comment]
Hi @luckoseabraham 
Thanks for the suggestion and the contribution as well! We'll look into it soon

**Comment by luckoseabraham** [comment]
Thanks @yaronya

**Comment by luckoseabraham** [comment]
Completed using PR #125
