### ISSUE TITLE
panic: invalid character 'p' looking for beginning of value

### ISSUE THREAD

**Issue by bisikuku** [env0/terratag#134]
Evaluating terratag for our environment trying to tag a module and i am getting the error below:
2022/05/07 09:03:47 [INFO] Processing file database/context.tf
panic: invalid character 'p' looking for beginning of value

goroutine 1 [running]:
github.com/env0/terratag/errors.PanicOnError(...)
        /home/runner/work/terratag/terratag/errors/errors.go:10
main.jsonToHclMap(0x7ffd814a1470, 0x4, 0xc0003be339, 0x7)
        /home/runner/work/terratag/terratag/main.go:145 +0x397
main.tagFileResources(0xc0003be330, 0x13, 0x7ffd814a145e, 0xb, 0xd54f30, 0x2, 0x7ffd814a1470, 0x4, 0x1, 0x1, ...)
        /home/runner/work/terratag/terratag/main.go:90 +0x148
main.tagDirectoryResources(0x7ffd814a145e, 0xb, 0xd54f30, 0x2, 0xc0003d8000, 0x7, 0x10, 0x7ffd814a1470, 0x4, 0x1, ...)
        /home/runner/work/terratag/terratag/main.go:72 +0x24b
main.Terratag(0x7ffd814a1470, 0x4, 0x7ffd814a145e, 0xb, 0xd54f30, 0x2, 0x10001)
        /home/runner/work/terratag/terratag/main.go:60 +0x13d
main.main()
        /home/runner/work/terratag/terratag/main.go:33 +0x10b

**Comment by yaronya** [comment]
@bisikuku thanks for the issue.
Please share a reproducible repo or some example for us to investigate it better. Quite hard to reproduce it otherwise

**Comment by bisikuku** [comment]
test repo : https://github.com/Azure-Terraform/terraform-azurerm-virtual-network

command: terratag -dir=./subnet/ -tags=$TAG

output:root@metal:~/mg/terraform-azurerm-virtual-network# terratag -dir=./subnet/ -tags=$TAG
2022/05/12 17:03:18 [INFO] Processing file subnet/output.tf
panic: invalid character 'p' looking for beginning of value

goroutine 1 [running]:
github.com/env0/terratag/errors.PanicOnError(...)
        /home/runner/work/terratag/terratag/errors/errors.go:10
main.jsonToHclMap(0x7ffcb07f6440, 0x4, 0xc00011c157, 0x6)
        /home/runner/work/terratag/terratag/main.go:145 +0x397
main.tagFileResources(0xc00011c150, 0x10, 0x7ffcb07f6430, 0x9, 0xd54f30, 0x2, 0x7ffcb07f6440, 0x4, 0x1, 0x1, ...)
        /home/runner/work/terratag/terratag/main.go:90 +0x148
main.tagDirectoryResources(0x7ffcb07f6430, 0x9, 0xd54f30, 0x2, 0xc00011e140, 0x4, 0x4, 0x7ffcb07f6440, 0x4, 0x1, ...)
        /home/runner/work/terratag/terratag/main.go:72 +0x24b
main.Terratag(0x7ffcb07f6440, 0x4, 0x7ffcb07f6430, 0x9, 0xd54f30, 0x2, 0x10001)
        /home/runner/work/terratag/terratag/main.go:60 +0x13d
main.main()
        /home/runner/work/terratag/terratag/main.go:33 +0x10b

**Comment by indu-sharma1** [comment]
That is the issue when your $TAG is Map not JSON string.  Yes, its a bug but when you don't use JSON string. 
For JSON string , it works. Example:  TAG = '{"test":"abc", "dnet":"1.10.1.0/24"}'

**Comment by bisikuku** [comment]
thank you for your response, will use it as advised.

**Comment by indu-sharma1** [comment]
I'd suggest to keep the bug open as following is still ad bug and is very useful when passing arguments from Jenkins or other tools. 

This doesn't work(This throws Panic error):
-tags="environment_id=prod,some-tag=value"

**Comment by bisikuku** [comment]
true, our primary tool is Jenkins. Will keep it open

**Comment by TomerHeber** [comment]
@indu-sharma1 and @bisikuku 
Have you tried the latest terratag version?

AFAIK `-tags="environment_id=prod,some-tag=value"` should now work as expected.
