### ISSUE TITLE
Support terragrunt

### ISSUE THREAD

**Issue by eladmosh** [env0/terratag#146]
### Some Intro
[terragrunt](https://terragrunt.gruntwork.io/) is a wrapper around `terrafrom` that provides extra tools for keeping your configurations DRY using a special file named `terragrunt.hcl` placed in your configuration folder.
It basically has 2 modes:

1. most common and simple mode is using a `terraform` block
```
terraform {
  source = "tfr:///terraform-aws-modules/vpc/aws?version=3.5.0"
}
```
In this case `terragrunt` will create a cache folder called `.terragrunt-cache` with some subfolders and at its last level it will download the terraform files from the `source` you just specified.

2. the second mode is using a `generate` block and then `include` this block in a different `terragrunt.hcl` file.
```
generate "provider" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "aws" {
  region = "us-east-1"
}
EOF
}
```
In this case the file will be created directly at the same folder as the `terragrunt.hcl` file without a cache folder.

**Note**: you can mix the 2 modes and in that case all files will be copied to the `.terragrunt-cache` folder.

### Expected Behavior 
Run `terratag` at the root folder of our configuration (where our `terragrunt.hcl` file is located) and tag the `*.tf` files.

### Actual Behavior 
currently if we try to run `terratag` in our configuration folder `terratag` will not detect any tagable terraform files.
The reason for this behavior is because `terragrunt` will copy the `*.tf` files to the `.terragrunt-cache` folder and not the `cwd` where we run the `terratag`.

## Possible Solution 
`terratag` should, in addition,  check if we have a `.terragrunt-cache` folder and if we do just travel down its subfolders until you find the folder with the copied `*.tf ` files and then start tagging.

<img width="335" alt="Screen Shot 2022-06-12 at 19 15 15" src="https://user-images.githubusercontent.com/93523957/173332064-f2279a99-919c-441a-a824-f0ea270dc9f2.png">

**Comment by TomerHeber** [comment]
Some initial thoughts (appreciate any feedback):

1. One issue with .terragrunt-cache is that the ".tf" files in it might get overrode (E.g. any time "terragrunt init" is called). Therefore modifying the cached files is likely not going to work.
2. There's an option to run a "before_hook" as described here: https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/ . It's possible to run terratag in the before hook.
3. So it's possible that terratag injects before_hook (assuming it works well) to the terragrunt hcl file.

Open to ideas and suggestions. (Right now I'm not sure how to proceed).

**Comment by yaronya** [comment]
@TomerHeber any reason to keep this issue opened after #147 was merged?

**Comment by TomerHeber** [comment]
@yaronya - I was thinking of adding an integration test.

**Comment by TomerHeber** [comment]
Working example:

main.tf
```
  resource "google_storage_bucket" "static-site" {
  name          = "image-store.com"
  location      = "EU"
  force_destroy = true

  website {
    main_page_suffix = "index.html"
    not_found_page   = "404.html"
  }
  cors {
    origin          = ["http://image-store.com"]
    method          = ["GET", "HEAD", "PUT", "POST", "DELETE"]
    response_header = ["*"]
    max_age_seconds = 3600
  }
  labels = {
    "foo" = "bar"
  }
}

locals {
  create_cmd_bin = "asdas"
  destroy_cmd_bin = "fsdfds"
  gcloud_bin_path = "fsdfsd"
  wait = "Fdfsd"
  skip_download = true
}
```

terragrunt.hcl
```
generate "provider" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<EOF
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

provider "google" {
  project     = "my-project-id"
  region      = "us-central1"
}
EOF
}


terraform {
  source = "tfr:///terraform-google-modules/gcloud/google?version=2.1.0"
}
```

**Comment by TomerHeber** [comment]
command:
`terratag -tags='{"cool":"boo"}' -type=terragrunt -rename=false`
`terragrunt validate`

**Comment by TomerHeber** [comment]
@yaronya - WDYT?
The above is a working example - should I invest time in writing a test for it.
* terragrunt init
* terratag...
* validate: terragrunt validate is successful.

**Comment by yaronya** [comment]
SGTM
Let's do it 💪

**Comment by TomerHeber** [comment]
@eladmosh - if I understand we should support the use case where ./.terraform is created instead of ./.terragrunt-cache ?
Please confirm and I will add this missing feature.

**Comment by eladmosh** [comment]
Hi @TomerHeber I already mentioned this use case [here](https://env0.slack.com/archives/C015Y0AJLQ7/p1655804277111059?thread_ts=1655115525.863579&cid=C015Y0AJLQ7) when the user of `terragrunt` only use `generate` blocks and doesn't have any `terraform` blocks.
In this case no cache folder will be created and all the `*.tf` files will be located in the `cwd`.
The solution for this, IMO, is to first look for the `.terragrunt-cache` folder and only if it exists look for the `*.tf` there, otherwise just look in the `cwd`.
Thank you dude.

**Comment by yaronya** [comment]
@TomerHeber @eladmosh hey guys what's the status of this issue? did we end up solving it completely?

**Comment by eladmosh** [comment]
@yaronya, @TomerHeber solved this issue, however the PR that updates the version of `terratag`  on `3rd-party.Dokcerfile` will only be deployed to `prod` tomorrow..

**Comment by TomerHeber** [comment]
@yaronya - Yes it's solved. The reason it's still open is that there is another acceptance test I wanted to add.

**Comment by yaronya** [comment]
@TomerHeber I see
Feel free to open a PR for it (without attaching an issue). The reason I want this closed is that users are expecting this so if we already released a working version - then I prefer closing it 😃
