### ISSUE TITLE
Chore: upgrade libraries and fix security issues

### ISSUE THREAD

**Issue by TomerHeber** [env0/terratag#156]
Upgrade the go libraries in go.mod.
This should fix reported security issues.

**Comment by yaronya** [comment]
Hi @TomerHeber 
Did we make the necessary upgrades?

**Comment by TomerHeber** [comment]
@yaronya 
Unfortunately no.
Please see my comment here: https://env0.slack.com/archives/C01QBBEGBEH/p1662832238704839?thread_ts=1662748901.448779&cid=C01QBBEGBEH

I may require some assistance. Thanks!
