### ISSUE TITLE
`terratag --version` command is broken

### ISSUE THREAD

**Issue by yaronya** [env0/terratag#168]
Since `0.2.0`, running `terratag --version` returns `vdev` instead of the expected version

It seems like we have two release patterns:
1. `goreleaser`
2. running `go build ...` and using that artifact when pushing to npm

The latter returns the falsy `vdev` version, while the former returns a valid version output.

We should also see if we can consolidate those in a way that the `npm publish` command will be triggered automatically when a release is created and will use the artifact of the `goreleaser`

**Comment by chpl** [comment]
can try https://www.npmjs.com/package/@pgollangi/go-npm
