### ISSUE TITLE
terratag inconsistent behaviour with the google-beta provider 

### ISSUE THREAD

**Issue by urie-tsec** [env0/terratag#172]
**Describe the bug**
In the case of both the google and the google-beta provider included resources from google will inconsistently get tagged and not necessarily according to provider 

**To Reproduce**
A minimal Terraform configuration reproducing the issue:  
```terraform
resource "google_compute_global_address" "global_ip" {
  project       = "test"
  name          = "test"
  address_type  = "type"
  address       = "1.2.3.4"
  network       = null
  purpose       = null
  prefix_length = 2
  ip_version    = "IPV4"
}

resource "google_compute_global_address" "global_ip2" {
  provider = google-beta
  project       = "test"
  name          = "test"
  address_type  = "type"
  address       = "1.2.3.4"
  network       = null
  purpose       = null
  prefix_length = 2
  ip_version    = "IPV4"
}
```

**Expected behavior**
Only the second resource would be tagged since it's the one using the google-beta provider

**Additional context**
It seems the issue started since https://github.com/env0/terratag/pull/167 was merged. It seems that when looking for the resource type currently the logic doesn't check the schema of the specific provider and because of that sometimes chooses the google provider and sometimes the google-beta provider

**Workaround**
I guess it's possible to try to only use `google` or `google-beta` provider but it's not that viable in most cases

**Comment by TomerHeber** [comment]
hi @urie-tsec 

Would you mind testing https://github.com/env0/terratag/pull/173 ?

**Comment by TomerHeber** [comment]
Hi @urie-tsec ,

I'm releasing a new version now. It should be available in the next 20 minutes.

**Comment by roni-frantchi** [comment]
@urie-tsec: @TomerHeber was referring to a new Terratag version which will be available in ~20 minutes.  

We're going to bump env0's version, test it and roll it out to production.  
It'll likely be live by end of day
