### ISSUE TITLE
google_monitoring_notification_channel only accepts email label/tag

### ISSUE THREAD

**Issue by away168** [env0/terratag#175]
**Describe the bug**
For google_monitoring_notification_channel resource, it only accept email. Any other labels added will cause error.
     {
       "type": "email",
       "displayName": "Email",
       "description": "A channel that sends notifications via email.",
       "labels": [
         {
           "key": "email_address",
           "description": "An address to send email."
         }
       ],
       "name": "projects/prj-vo-sec-n-iam-test/notificationChannelDescriptors/email",
       "launchStage": "GA"
     },

**To Reproduce** (TBD)
A minimal Terraform configuration reproducing the issue:  
```terraform

provider "" {

}

```

**Expected behavior**
Skip label of other keys other than email

**Screenshots**
(TBD)

**Desktop (please complete the following information):**
 TBD
Within env0

**Additional context**

**Workaround**
Please add how you worked around this problem, if so.

**Comment by TomerHeber** [comment]
Hi @away168 - could you please clarify?
Is the ask not to add labels to this resource type?

**Comment by away168** [comment]
Yes. The ask is to skip this resource.

**Comment by away168** [comment]
Closing for now - since SKIP environment variable was implemented : https://github.com/env0/terratag/pull/176
