### ISSUE TITLE
Support OpenTofu

### ISSUE THREAD

**Issue by Wassap124** [env0/terratag#184]
The terraform command and opentofu commands are identical,
except for using the `tofu` CLI instead of `terraform` CLI

terratag should support both

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

It can be included to terratag.
