### ISSUE TITLE
FR: set `volume_tags` on `aws_instance` resource

### ISSUE THREAD

**Issue by chpl** [env0/terratag#186]
**Is your feature request related to a problem? Please describe.**
The [aws_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance) resource creates an ebs volume, but the tags are not applied to it.
See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#tags
> Note that these tags apply to the instance and not block storage devices

**Describe the solution you'd like**
There's [volume_tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#volume_tags) attribute that controls volume tags, terratag should set it too.

**Describe alternatives you've considered**
Another option is to manage volumes as separate resource and attach them using `aws_volume_attachment` but this won't work for root volume.

**Additional context**
n/a

**Comment by sachin-ks** [comment]
@TomerHeber sample file:
`resource "aws_instance" "ubuntu" {
  ami = var.ami_id
  instance_type = "t3.micro"
  availability_zone = "us-west-2"


  tags = {
    Name = "terratag-test"
    env = "test"
  }
  volume_tags = {
    env = "test"
  }
}`

OR:
`resource "aws_instance" "ubuntu" {
  ami = var.ami_id
  instance_type = "t3.micro"
  availability_zone = "us-west-2"


  tags = {
    Name = "terratag-test"
    env = "test"
  }
}`

**Comment by terenho-jobber** [comment]
The PR #187 introduces a conflict error. I have more details in https://github.com/env0/terratag/pull/187#issuecomment-1972176814. Should I open a new issue or reopen this one?

**Comment by TomerHeber** [comment]
@terenho-jobber - if you can open a new issue I will greatly appreciate that.
Thanks!
