### ISSUE TITLE
Print schema output error when we get it

### ISSUE THREAD

**Issue by HeverFarber** [env0/terratag#202]
**Describe the bug**
We are getting an unknown error when `terratag` running 

```
2024/10/17 23:05:52 [ERROR] failed to process .terragrunt-cache/ZiUg9h_uAevILi4U8K_wv5sMsoY/JdgpqCHyTuP5A8pJxv9GYsCMYqc/....../main.tf due to an error failed to execute 'terraform providers schema -json' command: exit status 1
```

We don't print the the TF logs in any way only the [error status](https://github.com/env0/terratag/blob/c131667237dec941db5d25c11cd139b8e5ffb2a8/internal/tfschema/tfschema.go#L177) 

**Expected behavior**
Print the output and the error using https://pkg.go.dev/os/exec#Cmd.CombinedOutput
Also, print the [dir](https://github.com/env0/terratag/blob/c131667237dec941db5d25c11cd139b8e5ffb2a8/internal/tfschema/tfschema.go#L173) in case of error to check where we run it

**Comment by TomerHeber** [comment]
Closing issue. Let's create a new one, once we observe the error.
