### ISSUE TITLE
Add support for azapi

### ISSUE THREAD

**Issue by Constantine19** [env0/terratag#207]
**Is your feature request related to a problem? Please describe.**
Terratag does not tag resources created using azapi. After reviewing, it appears that terratag currently supports hashicorp/azurerm and hashicorp/azurestack for cost monitoring, but not azapi, which our prospect uses. This limits its applicability for their Azure environment.

**Describe the solution you'd like**
Add support for azapi in terratag to ensure tagging works for resources created with this provider

**Describe alternatives you've considered**
Asking the prospect to switch to hashicorp/azurerm or hashicorp/azurestack (not feasible due to their existing setup)

**Additional context**
The prospect uses azapi extensively in their Azure infrastructure. Adding support for it would improve compatibility and expand terratag's adoption.

**Comment by TomerHeber** [comment]
This is done.
