### ISSUE TITLE
azapi - not all resources support tags

### ISSUE THREAD

**Issue by hbuckle** [env0/terratag#209]
**Describe the bug**

Support was added in 0.5.1 for tagging azapi resources, but not all resources in ARM support tags (particularly sub-resources), leading to errors at plan time.

**To Reproduce**

```terraform

data "azurerm_client_config" "current" {}

data "azurerm_container_app" "example" {
  name                = "example"
  resource_group_name = "example"
}

resource "azapi_resource" "example" {
  type      = "Microsoft.App/containerApps/authConfigs@2024-03-01"
  name      = "current"
  parent_id = data.azurerm_container_app.example.id
  body = {
    properties = {
      globalValidation = {
        redirectToProvider          = "azureactivedirectory"
        unauthenticatedClientAction = "RedirectToLoginPage"
      }
      identityProviders = {
        azureActiveDirectory = {
          enabled           = true
          isAutoProvisioned = false
          registration = {
            clientId                = "example"
            clientSecretSettingName = "microsoft-provider-authentication-secret"
            openIdIssuer            = "https://sts.windows.net/${data.azurerm_client_config.current.tenant_id}/v2.0"
          }
          validation = {
            allowedAudiences = [
              "example",
            ]
            defaultAuthorizationPolicy = {
              allowedApplications = [
                "example",
              ]
            }
          }
        }
      }
      login = {}
      platform = {
        enabled        = true
        runtimeVersion = "~2"
      }
    }
  }
}

```

```
terratag -default-to-terraform -rename=false -tags="{\"test\":\"test\"}" -type=terraform -verbose
terraform plan
```

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid configuration
│
│   with azapi_resource.example,
│   on main.tf line 8, in resource "azapi_resource" "example":
│    8: resource "azapi_resource" "example" {
│
│ embedded schema validation failed: the argument "body" is invalid:
│ `tags` is not expected here. Do you mean `properties`?

**Expected behavior**

I'm not sure what the best way to handle this is - we can use the `-filter` option as a workaround, but there are so many of these sub-resources in ARM I feel like that would become unworkable.
I'm also not sure there is any way to handle this from the terratag side, it seems like the azapi provider is doing some dynamic validation at plan time.

**Desktop (please complete the following information):**

 - OS: Any
 - Terraform version: 1.9.8
 - Providers/module versions if applicable: azapi 2.0.1

**Comment by hbuckle** [comment]
For now I've just excluded all azapi resources with the filter option

**Comment by TomerHeber** [comment]
@hbuckle this is indeed a challenge.

maybe a white list approach.


E.g asking ourselves what type of resources we would like to tag.


type      = "Microsoft.App/containerApps/* is a no...
But do you have types that are a "yes" ?

**Comment by TomerHeber** [comment]
Please confirm that this is what we're looking for:
https://github.com/tfitzmac/resource-capabilities/blob/main/tag-support.csv

**Comment by hbuckle** [comment]
I haven't seen that list before, I note it hasn't been updated in some time though...

**Comment by hbuckle** [comment]
> @hbuckle this is indeed a challenge.
> 
> maybe a white list approach.
> 
> E.g asking ourselves what type of resources we would like to tag.
> 
> type = "Microsoft.App/containerApps/* is a no... But do you have types that are a "yes" ?

I'm not sure if there is a good way to tell just from the resource type - it isn't really consistent, some sub-resources do support tags and some don't

**Comment by TomerHeber** [comment]
this is more up-to-date:
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support

allow me some time to review and come up with a solution.
using the information above will hopefully suffice.

**Comment by hbuckle** [comment]
I may take a look at the azapi provider and see if it can be addressed there - as they are allowing the tags property to be set even if the underlying resource doesn't support it.

**Comment by TomerHeber** [comment]
from your example above, and https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support
the resource should support tags. I would suggest checking it as well... Microsoft may need to update their documentation... or fix bugs...

**Comment by hbuckle** [comment]
Which resource do you mean sorry?

**Comment by TomerHeber** [comment]
the one from your example:
 type      = "Microsoft.App/containerApps/authConfigs@2024-03-01"

**Comment by hbuckle** [comment]
Yes, so `Microsoft.App/containerApps` does support tags, but `Microsoft.App/containerApps/authConfigs` doesn't

[containerApps](https://learn.microsoft.com/en-us/rest/api/resource-manager/containerapps/container-apps/create-or-update?view=rest-resource-manager-containerapps-2024-03-01&tabs=HTTP#request-body)

[containerApps/authConfigs](https://learn.microsoft.com/en-us/rest/api/resource-manager/containerapps/container-apps-auth-configs/create-or-update?view=rest-resource-manager-containerapps-2024-03-01&tabs=HTTP#request-body)

**Comment by TomerHeber** [comment]
Hi @hbuckle -

I created a PR that white lists resources based on Microsoft's documentation.
Feel free to test.

https://github.com/env0/terratag/pull/210
https://github.com/env0/terratag/tree/fix-azapi-whitelist-%23209

**Comment by TomerHeber** [comment]
Hi @hbuckle - I'm releasing a new version.
Feel free to try it out, and let me know if it resolves your issues.

**Comment by hbuckle** [comment]
@TomerHeber - thanks for addressing this, it seems to work. Hopefully the documentation page format will not change too much

**Comment by TomerHeber** [comment]
> @TomerHeber - thanks for addressing this, it seems to work. Hopefully the documentation page format will not change too much

Great! Thanks for following up.
We have an easy path to update it if needed.

Fortunately, it's a whitelist. As long as there are no documentation errors or Microsoft decides to remove tags, it should be fine.
