### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by BarakBD-Globality** [env0/terratag#53]
**cluster/ecs.tf**
```hcl
resource "aws_ecs_cluster" "cluster" {
  count = var.cluster_count
  name  = "${local.name}-${var.environment}${count.index > 0 ? count.index + 1 : ""}"
  setting {
    name = "containerInsights"
    # disabling for all clusters.
    # To turn off for devX, just change the first "enabled" to "disabled"
    value = count.index > 0 ? "enabled" : "enabled"
  }
}
```

$ terratag -tags={\"environment_id\": \"prod\"}
2020/09/24 23:04:15 Processing file cluster/ecs.tf
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/env0/terratag/errors.PanicOnError(...)
        /home/runner/work/terratag/terratag/errors/errors.go:10
main.jsonToHclMap(0x7ffeefbfeaf7, 0x12, 0xc000406b78, 0x3)
        /home/runner/work/terratag/terratag/main.go:97 +0x385
main.tagFileResources(0xc000406b70, 0xe, 0x19d3f5d, 0x1, 0x7ffeefbfeaf7, 0x12, 0xd)
        /home/runner/work/terratag/terratag/main.go:55 +0x148
main.tagDirectoryResources(0x19d3f5d, 0x1, 0xc00043e000, 0x5c, 0x80, 0x7ffeefbfeaf7, 0x12, 0x1f47901, 0xd)
        /home/runner/work/terratag/terratag/main.go:42 +0x1c8
main.Terratag()
        /home/runner/work/terratag/terratag/main.go:34 +0xf9
main.main()
        /home/runner/work/terratag/terratag/main.go:20 +0x25

terraform 0.13.3

**Comment by roni-frantchi** [comment]
Hey @BarakBD-Globality thanks for reporting this issue!  
We couldn't reproduce the issue as it was reported - 
We had tried to, and finally the only way we could force reproduce this error is by running passing in a malformed `terratag -tags` likes so:  
```
terratag -tags='{"environment_id": "prod}'
```

Any chance that's what happened there?
