### ISSUE TITLE
Allow non-map tags

### ISSUE THREAD

**Issue by BarakBD-Globality** [env0/terratag#54]
$ terratag -tags=var.default_tags
2020/09/24 23:09:46 Processing file cluster/ecs.tf
panic: invalid character 'v' looking for beginning of value

**Comment by yaronya** [comment]
Hi @BarakBD-Globality 
Can you please elaborate on your use case?
`terratag` is executed via shell, which doesn't have native access to the TF variables scope.

**Comment by yaronya** [comment]
@TomerHeber let's implement this to support simple key value pairs, delimited by command (i.e `key1=value,key2=value2`)

**Comment by TomerHeber** [comment]
@yaronya 
Something like this:
`terratag key1=value1,key2=value2 ...`
or
`terratag -tags='key1=value1,key2=value2' ...`
or something else?

**Comment by yaronya** [comment]
> @yaronya Something like this: `terratag key1=value1,key2=value2 ...` or `terratag -tags='key1=value1,key2=value2' ...` or something else?

@TomerHeber I think the latter is required (i.e `-tags='key1=value1,key2=value2'`) as we're already using the `tags` as required flag and don't use some default parameter like the former.
