### ISSUE TITLE
Support retries for tfschema

### ISSUE THREAD

**Issue by RLRabinowitz** [env0/terratag#57]
`tfschema` might sometimes fail because of one-time issues, for example: `panic: Failed to NewClient: Failed to initialize NetRPC plugin: timeout while waiting for plugin to start`.

Including an option to support retries on `tfschema.NewClient` might be worthwhile, and should prevent errors in tagging because of temporary `tfschema` issues

**Comment by RLRabinowitz** [comment]
After fixing https://github.com/env0/terratag/issues/59, this issue might not be necessary. We should keep a lookout to see if any `tfschema` issues still happen

**Comment by roni-frantchi** [comment]
> After fixing #59, this issue might not be necessary. We should keep a lookout to see if any tfschema issues still happen

I agree, I think #59 should do it.
