### ISSUE TITLE
GHA displays terratag logs as errors under summary "annotations"

### ISSUE THREAD

**Issue by RLRabinowitz** [env0/terratag#75]
### Summary

When executing the terratag GitHub Action, terratag logs are considered errors on GitHub Action "Summary", even though the job passes.

### Steps to reproduce

1. Fork RLRabinowitz/terratag-gha-log-error
2. Commit on main branch
3. Take a look at the action once it's finished

### Error

![Screen Shot 2021-01-03 at 14 33 11](https://user-images.githubusercontent.com/30493345/103478757-892f1580-4dd1-11eb-878b-159779f71922.png)

**Comment by yaronya** [comment]
After discussing with @RLRabinowitz, this seems related to the terratag's GH action and not terratag itself
