### ISSUE TITLE
Remove buildMapExpression (probably not needed)

### ISSUE THREAD

**Issue by avnerenv0** [env0/terratag#79]
After #76 I'm pretty sure we don't need to `buildMapExpression` as we do in `convert.go`.
#76 made us stop entering the altered tags as Strings, so the original formats of the maps should work.
This needs to be validated.
Also might worth checking if we can close some issues like #9 and #32

**Comment by TomerHeber** [comment]
@avnerenv0 - could you please give me additional details as to what I might need to remove.
Note: that at the moment, when running tests the function `buildMapExpression` is called and used.

**Comment by avnerenv0** [comment]
The original intention was that in #76 we moved to a more robust way of creating the `tokens`. I thought that this could mean that the `GetExistingTagsExpression` function could always call `stringifyExpression` and that we didn't need to give Maps a different treatment. That would mean deleting quite a bit of code in `convert.go`.

(If it works - The tests might give a little different formatting, see most of #76 as an example)

As the description says - I never validated this. So I guess you can just try removing that `if` and seeing what the tests give out. I wouldn't chase it further than that.
