### ISSUE TITLE
Terraform 1.0.0 support

### ISSUE THREAD

**Issue by matthewhembree** [env0/terratag#89]
Fails on 1.0.0

```
terratag -tags='{ "source_repo": "corp/repo/path" }' -verbose-true
2021/06/14 13:11:47 Unable to parse 'terraform version'

❯ terraform version
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
```

Thanks!

**Comment by RLRabinowitz** [comment]
Thanks for bringing this to our attention!
We'll look into it

**Comment by roni-frantchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Terratag fails on TF v1.0.0](https://trello.com/c/FfuAqVar/3481-terratag-fails-on-tf-v100)
