### ISSUE TITLE
terraform init must run before running terratag in already initialised directory

### ISSUE THREAD

**Issue by fraserc182** [env0/terratag#91]
Hi, I am using the example from the readme and getting errors.
```
 terratag -dir=foo/bar -tags={\"environment_id\": \"prod\"}
```
And this gives me the following error:
```
2021/07/18 21:37:08 terraform init must run before running terratag
```
However, obviously I have ran terraform init before doing this and it still gives me the same error. Any ideas?
I am using TF v1.0.1

**Comment by omry-hay** [comment]
Hi @fraserc182,

First thanks for trying out Terratag and open this issue.
I've tried to reproduced it but couldn't, so I might need some help figure this one out.

As you can see in [this function](https://github.com/env0/terratag/blob/f8f06a1281c58945f7fca0ffd05a7efe8729f925/terraform/terraform.go#L68) we are trying to see if `terraform init` command took place by looking for the `.terraform` folder that was created during the init phase.
This folder is a hidden folder and should be inside your Terraform folder, and also means that Terratag needs to run inside the same folder where the Terraform code is.

If this the case and you still gets an error please send us the folder structure and see if you can find the `.terraform` folder when running Terratag.

Thanks
