### ISSUE TITLE
VMWare Support? 

### ISSUE THREAD

**Issue by flickerfly** [env0/terratag#96]
I see AWS, GCP and Azure are supported. Is there any interest in supporting VMWare also?

**Comment by omry-hay** [comment]
Hi @flickerfly,
Thanks for opening an issue about this.
We are thinking of adding VMWare support as well, but we currently don't have a timeline for that.

We heard some people asking for VMWare support mainly around [VMware vSphere Provider](https://registry.terraform.io/providers/hashicorp/vsphere/latest).

Thanks

**Comment by omry-hay** [comment]
> @omry-hay - this is an example of a basic VShpere tagging configuration https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/tag#using-tags-in-a-supported-resource
> 
> First, create a category, then create a tag and assign the category to it, and finally assign the tag to resources.
> 
> https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/tag_category https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/tag
> 
> In general, we could try to add support for it (with the category adding a certain complexity to it).
> 
> A few questions:
> 
> 1. Is it something you still want to support? (given 6 months have passed).
> 2. I'm assuming the focus should be on the official Hashicorp Vshpere provider. (just confirming).

Hi @TomerHeber 

1. We would definatly would like to support it, in terms of priority please take it with @yaronya 
2. Yes.

Thanks

**Comment by yaronya** [comment]
Hi @TomerHeber 
Any updates on this one?

**Comment by TomerHeber** [comment]
Hi @yaronya 

I haven't started working on it.
Weren't sure about priority. Just say the word and I'll start working on this.

**Comment by yaronya** [comment]
@TomerHeber this is indeed low priority atm, let's continue with other efforts and get back to it when we got some spare time 🤞

**Comment by yaronya** [comment]
Closed as it seems ROI negative at the moment since there's not much demand for this feature
